import { CaseStudy } from '@/types/database';

export const INITIAL_CASE_STUDIES: CaseStudy[] = [
  {
    id: 'cs-01',
    name: 'Aethelgard AI',
    slug: 'aethelgard-ai',
    one_liner: 'Autonomous neural consensus infrastructure for next-gen synthetic research networks.',
    category: 'AI',
    year: '2024',
    accent_color: '#C6A15B',
    featured: true,
    sort_order: 1,
    status: 'published',
    client_name: 'Aethelgard Labs (Zurich)',
    services: ['Brand Architecture', 'Visual Identity', 'Design System', '3D Motion Design'],
    hero_image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'StudioFlag transformed our esoteric mathematical thesis into a visceral, iconic visual language that closed our $48M Series B.',
    challenge: 'Aethelgard pioneered a breakthrough distributed intelligence protocol, but their technical documentation looked like a dense cryptographic textbook. They needed a distinct aesthetic that felt both timelessly institutional and aggressively avant-garde.',
    approach: 'We designed a visual system grounded in bespoke typography, architectural grid layouts, and kinetic 3D glyphs derived from high-dimensional topology graphs. The identity uses deep black ink and warm brass accents to evoke the quiet prestige of century-old scientific academies.',
    outcome: 'A complete identity rollout across web, hardware server chassis, and brand collateral. The brand launch was featured across Fast Company and Wallpaper*, helping secure Tier-1 institutional research partnerships.',
    gallery_images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'cs-02',
    name: 'Vanguard Capital',
    slug: 'vanguard-capital',
    one_liner: 'Private liquidity networks and algorithmic wealth management for sovereign family offices.',
    category: 'Fintech',
    year: '2024',
    accent_color: '#8A9A87',
    featured: true,
    sort_order: 2,
    status: 'published',
    client_name: 'Vanguard Private Trust',
    services: ['Strategic Positioning', 'Editorial Design', 'Interactive Dossiers', 'Packaging'],
    hero_image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'A rare partner who understands the nuance of discretion, high finance, and understated luxury.',
    challenge: 'Ultra-high-net-worth liquidity services often suffer from either cold corporate banking aesthetics or noisy neon fintech tropes. Vanguard required extreme sophistication, tactile physical presence, and bespoke digital portals.',
    approach: 'We built a bespoke "Private Dossier" design language. Physical security devices bound in vegetable-tanned leather, heavy cotton letterpress identity suites, and an ultra-secure client portal utilizing quiet typographic hierarchy and subtle brass micro-interactions.',
    outcome: 'Over $2.1B in managed sovereign assets onboarded within 90 days of launch, with client retention reaching 100%.',
    gallery_images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-02-10T11:00:00Z',
  },
  {
    id: 'cs-03',
    name: 'Terraform Oceanic',
    slug: 'terraform-oceanic',
    one_liner: 'Deep-ocean carbon mineral capture and ecological restoration technology.',
    category: 'Climate',
    year: '2024',
    accent_color: '#5E8B7E',
    featured: true,
    sort_order: 3,
    status: 'published',
    client_name: 'Terraform Marine Institute',
    services: ['Brand Strategy', 'Environmental Graphics', 'Data Visualization', 'Digital Platform'],
    hero_image: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'They captured the colossal scale of oceanic engineering while maintaining razor-sharp scientific precision.',
    challenge: 'Communicating sub-surface geological sequestration without falling into generic green leaf clichés or alarmist tropes.',
    approach: 'Engineered an oceanographic data aesthetic featuring bathymetric contours, deep oceanic tones, and live telemetry dashboards.',
    outcome: 'Awarded Climate Innovation Brand of the Year and partnered with 14 coastal government authorities.',
    gallery_images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1498084393753-b411b2d26b34?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-03-01T09:00:00Z',
  },
  {
    id: 'cs-04',
    name: 'Lexis Juris',
    slug: 'lexis-juris',
    one_liner: 'AI-assisted dispute arbitration and cross-border maritime jurisprudence.',
    category: 'Legal',
    year: '2024',
    accent_color: '#A08060',
    featured: false,
    sort_order: 4,
    status: 'published',
    client_name: 'Lexis Consortium London',
    services: ['Identity System', 'Editorial Typography', 'Case Management UI'],
    hero_image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'The gravitas of century-old chambers married with the velocity of digital law.',
    challenge: 'Reinventing legal dossier management for supreme court counsel handling multi-jurisdictional commerce.',
    approach: 'Classical legal typesetting meets structured markdown workflows, monospaced annotation margins, and brass seal iconography.',
    outcome: 'Adopted by 45 top-tier global litigation firms across London, Geneva, and Singapore.',
    gallery_images: [
      'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-03-20T14:00:00Z',
  },
  {
    id: 'cs-05',
    name: 'Monolith Protocol',
    slug: 'monolith-protocol',
    one_liner: 'Zero-knowledge computational layers for enterprise verifiable intelligence.',
    category: 'Crypto',
    year: '2024',
    accent_color: '#B59458',
    featured: true,
    sort_order: 5,
    status: 'published',
    client_name: 'Monolith Research Ltd.',
    services: ['Brand Strategy', 'Protocol Docs Identity', 'Hardware Key Packaging'],
    hero_image: 'https://images.unsplash.com/photo-1639762681057-4082594a10d9?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'They turned abstract zero-knowledge proofs into an undeniable design monument.',
    challenge: 'Differentiating from scam-ridden crypto hype by crafting an uncompromising, architectural permanence.',
    approach: 'Monolithic concrete brutalist inspiration, matte black finishes, and laser-etched stainless steel hardware credentials.',
    outcome: 'Secured $1.4B in total value locked within first testnet launch.',
    gallery_images: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-04-05T08:30:00Z',
  },
  {
    id: 'cs-06',
    name: 'Soma Neurotech',
    slug: 'soma-neurotech',
    one_liner: 'Non-invasive circadian frequency modulation and deep sleep cognitive restoration.',
    category: 'Wellness',
    year: '2024',
    accent_color: '#7E9181',
    featured: false,
    sort_order: 6,
    status: 'published',
    client_name: 'Soma Health Kyoto',
    services: ['Industrial Design Language', 'Mobile App', 'Packaging', 'Sound Identity'],
    hero_image: 'https://images.unsplash.com/photo-1512290900672-1f02e60f0653?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'A sensory identity that genuinely brings calm before you even turn on the device.',
    challenge: 'Bridging high-precision medical EEG tech with serene Japanese ritual aesthetics.',
    approach: 'Silk-touch matte surfaces, minimalist biomorphic waveforms, and quiet ambient typography.',
    outcome: 'Sold out first 10,000 units in under 4 minutes with zero paid acquisition.',
    gallery_images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-04-18T16:00:00Z',
  },
  {
    id: 'cs-07',
    name: 'Atelier Kura',
    slug: 'atelier-kura',
    one_liner: 'Adaptive spatial architecture and regenerative residential sanctuaries.',
    category: 'Architecture',
    year: '2023',
    accent_color: '#D4A373',
    featured: true,
    sort_order: 7,
    status: 'published',
    client_name: 'Kura Spatial Works (Tokyo)',
    services: ['Editorial Monograph', 'Web Experience', 'Material Sample Boxes'],
    hero_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'The digital portfolio feels like stepping into a serene timber pavilion.',
    challenge: 'Translating the tactile resonance of cedar, hand-troweled plaster, and light into digital form.',
    approach: 'High-definition full bleed editorial spreads, acoustic sound design, and custom Fraunces serif titling.',
    outcome: 'Featured in Architectural Digest and commissioned for 8 private island estates.',
    gallery_images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2023-11-12T13:00:00Z',
  },
  {
    id: 'cs-08',
    name: 'Canis & Co.',
    slug: 'canis-and-co',
    one_liner: 'Cellular canine longevity diagnostics and genomic clinical nutrition.',
    category: 'Pets',
    year: '2024',
    accent_color: '#C49752',
    featured: false,
    sort_order: 8,
    status: 'published',
    client_name: 'Canis Longevity Inc.',
    services: ['Brand Strategy', 'Diagnostic Kit Packaging', 'Direct-to-Consumer UI'],
    hero_image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'Elevating veterinary science to the level of haute cuisine and clinical excellence.',
    challenge: 'Avoiding standard cartoony pet food branding to appeal to discerning owners seeking longevity science.',
    approach: 'Pharmaceutical precision packaging combined with rich portraiture and clear genetic biomarkers.',
    outcome: 'Over 85,000 active monthly subscribers across North America.',
    gallery_images: [
      'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-05-02T10:30:00Z',
  },
  {
    id: 'cs-09',
    name: 'Aeris Aerodynamics',
    slug: 'aeris-aerodynamics',
    one_liner: 'Computational fluid dynamics and ultra-lightweight composite track bicycles.',
    category: 'Sports',
    year: '2023',
    accent_color: '#E06D53',
    featured: false,
    sort_order: 9,
    status: 'published',
    client_name: 'Aeris Velodrome Team',
    services: ['Frame Livery Design', 'Telemetry App', 'Brand Film'],
    hero_image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'A visual identity engineered for 70 km/h wind tunnels.',
    challenge: 'Showcasing micro-drag aerodynamic improvements with high-speed kinetic appeal.',
    approach: 'Wind tunnel streak lines, raw carbon fiber textures, and neon optical markers.',
    outcome: 'Olympic gold medal victory in team pursuit with global media acclaim.',
    gallery_images: [
      'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2023-09-20T15:45:00Z',
  },
  {
    id: 'cs-10',
    name: 'Helios Grid',
    slug: 'helios-grid',
    one_liner: 'Next-generation virtual power plant orchestration for decentralized microgrids.',
    category: 'SaaS',
    year: '2024',
    accent_color: '#D89E3A',
    featured: true,
    sort_order: 10,
    status: 'published',
    client_name: 'Helios Energy Group',
    services: ['Product Design System', 'Executive Dashboard', 'Identity Refresh'],
    hero_image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'Transforms gigawatts of erratic renewable power into an elegant, real-time command center.',
    challenge: 'Enterprise energy software is notoriously outdated and difficult for operators to parse during grid strain.',
    approach: 'Sub-second real-time telemetry visual system with dark-mode contrast optimized for 24/7 control rooms.',
    outcome: 'Deployed across 12 European national power operators managing 4.8 GW capacity.',
    gallery_images: [
      'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-05-19T09:15:00Z',
  },
  {
    id: 'cs-11',
    name: 'Quanta Photonics',
    slug: 'quanta-photonics',
    one_liner: 'Room-temperature optical quantum computing chips and laser waveguides.',
    category: 'Tech',
    year: '2024',
    accent_color: '#6C8EA4',
    featured: false,
    sort_order: 11,
    status: 'published',
    client_name: 'Quanta Photonics Silicon Labs',
    services: ['Brand System', 'Wafer Macro Photography', 'Investor Portal'],
    hero_image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'A visual celebration of light, diffraction, and unimaginable computation speed.',
    challenge: 'Presenting invisible silicon photonic waveguide physics to institutional hardware investors.',
    approach: 'Iridescent optical diffraction textures, clean micro-typography, and macro microscopy imagery.',
    outcome: 'Oversubscribed $90M Series C round led by premier semiconductor syndicates.',
    gallery_images: [
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-06-02T12:00:00Z',
  },
  {
    id: 'cs-12',
    name: 'Aura Spatial Audio',
    slug: 'aura-spatial-audio',
    one_liner: 'Binaural psychoacoustic render engine for hyper-realistic immersive audio.',
    category: 'Tech',
    year: '2024',
    accent_color: '#B288C0',
    featured: false,
    sort_order: 12,
    status: 'published',
    client_name: 'Aura Sound Labs',
    services: ['Acoustic Identity', 'Developer SDK Portal', 'Audio Plugin GUI'],
    hero_image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'The interface feels like manipulating invisible 3D sonic sculptures in mid-air.',
    challenge: 'Designing spatial sound controls for music producers without cluttered faux-analog knobs.',
    approach: 'Volumetric ray-traced spatial spheres, vector precision dials, and haptic feedback design.',
    outcome: 'Integrated into top AAA game engines and Grammy-winning Dolby Atmos production suites.',
    gallery_images: [
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-06-15T17:30:00Z',
  },
  {
    id: 'cs-13',
    name: 'Hyperion Biofuels',
    slug: 'hyperion-biofuels',
    one_liner: 'Genetically engineered microalgae aviation fuels for zero-emission intercontinental flight.',
    category: 'Climate',
    year: '2023',
    accent_color: '#4E9F76',
    featured: false,
    sort_order: 13,
    status: 'published',
    client_name: 'Hyperion Sustainable Aviation',
    services: ['Strategic Brand Dossier', 'Bioreactor Signage', 'Keynote Presentations'],
    hero_image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'Gave our biological engineering company the poise of a century-old aerospace leader.',
    challenge: 'Bridging bio-engineering lab aesthetics with aviation certification and airline fleet partnerships.',
    approach: 'Precision technical blueprint styling, mossy photosynthetic greens, and titanium accents.',
    outcome: 'First transatlantic flight powered by 100% Hyperion SAF completed successfully.',
    gallery_images: [
      'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2023-10-04T11:20:00Z',
  },
  {
    id: 'cs-14',
    name: 'Veritas Governance',
    slug: 'veritas-governance',
    one_liner: 'Institutional governance protocols and cryptographic treasury auditing for DAOs.',
    category: 'Legal',
    year: '2024',
    accent_color: '#8A9A87',
    featured: false,
    sort_order: 14,
    status: 'published',
    client_name: 'Veritas Foundation (Zug)',
    services: ['Governance UI', 'Charter Publication Design', 'Seal Design'],
    hero_image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'A masterclass in establishing democratic trust through editorial visual structure.',
    challenge: 'Making complex quadratic voting and multi-sig proposals accessible to diverse global delegates.',
    approach: 'Parliamentary gazette typography, high-clarity ballot flows, and verified cryptographic badges.',
    outcome: 'Governing over $6B in protocol treasuries with zero contested voting incidents.',
    gallery_images: [
      'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-07-01T14:40:00Z',
  },
  {
    id: 'cs-15',
    name: 'Kallisto Robotics',
    slug: 'kallisto-robotics',
    one_liner: 'Bipedal warehouse logistics androids and dynamic terrain spatial navigation.',
    category: 'AI',
    year: '2024',
    accent_color: '#D17B49',
    featured: false,
    sort_order: 15,
    status: 'published',
    client_name: 'Kallisto Heavy Industries',
    services: ['Industrial Robot Livery', 'Fleet Teleoperation UI', 'Hardware Design System'],
    hero_image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'Humanoid robots that look like pieces of industrial high-end sculpture rather than cold plastic.',
    challenge: 'Humanizing bipedal machinery without uncanny valley gimmicks.',
    approach: 'Warm anodized bronze casing accents, friendly status ring animations, and clear spatial glyphs.',
    outcome: 'Signed commercial deployment across 20 global fulfillment facilities.',
    gallery_images: [
      'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-07-20T16:10:00Z',
  },
  {
    id: 'cs-16',
    name: 'Zephyr Vault',
    slug: 'zephyr-vault',
    one_liner: 'Private alpine underground archival vaults and precious asset tokenization.',
    category: 'Fintech',
    year: '2024',
    accent_color: '#C6A15B',
    featured: false,
    sort_order: 16,
    status: 'published',
    client_name: 'Zephyr Alpine Security AG',
    services: ['Brand Monograph', 'Keycard Material Sourcing', 'Client Vault UI'],
    hero_image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1800&q=85',
    pull_quote: 'Impenetrable Swiss fortress security expressed through delicate editorial craftsmanship.',
    challenge: 'Communicating the physical invulnerability of deep-granite Swiss vaults to digital collectors.',
    approach: 'Granite and gold foil monograph printing, bespoke mono numbering, and tactile cryptographic keys.',
    outcome: '100% capacity reserved prior to the official vault opening ceremony in St. Moritz.',
    gallery_images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    created_at: '2024-08-01T09:00:00Z',
  },
];
